// Generated by scripts/sync-changelog.mjs — do not edit by hand.
export const releases: Record<string, { version: string; date: string }> = {
  'expo-devtools': { version: '3.4.0', date: '1 October 2026' },
  'react-native-devtools-tab': { version: '0.1.2', date: '28 September 2026' },
  'react-pretty-print': { version: '0.1.1', date: '28 September 2026' },
};
